name: dash_mement
description: DDD7_dash_project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  google_maps_flutter: ^2.1.5
  geolocator: ^8.2.1
  dio: ^4.0.0
  connectivity_plus: ^1.0.7
  location: ^4.3.0
  permission_handler: ^8.1.4+2
  flutter_svg: ^0.22.0
  provider: ^6.0.0
  cached_network_image: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  flutter_screenutil: ^5.5.3+2
  carousel_slider: ^4.1.1
  youtube_player_flutter: ^8.1.0
  animated_overflow: ^2.0.0
  image_picker: ^0.8.5+3
  lottie: ^1.3.0
  fluttertoast: ^8.0.9
  flutter_native_splash: ^2.2.0

flutter:

  uses-material-design: true
  assets:
    - assets/styles/
    - assets/svgs/
    - assets/json/
    - assets/test/
    - assets/images/
    - assets/gif/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
